[package]
edition = "2024"
name = "tofu"
publish = false
version = "1.1.0"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
topcoat = { version = "0.6.2", features = ["tower"] }
tower = "0.5.3"
tower-http = { version = "0.7.1", features = ["fs"] }

[dev-dependencies]
anyhow = "1.0.104"

[build-dependencies]
reqwest = "0.13.4"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
zip = "8.6.0"
